P8105 HW2
================
Yutong Mao (UNI: ym3139)
2025-10-01

# Problem 1

``` r
library(tidyverse)

# --- Load data ---
pols  <- readr::read_csv("data/fivethirtyeight_datasets/pols-month.csv")
snp   <- readr::read_csv("data/fivethirtyeight_datasets/snp.csv")
unemp <- readr::read_csv("data/fivethirtyeight_datasets/unemployment.csv")
```

``` r
pols_clean <- pols |>
  tidyr::separate(
    mon, into = c("year", "month_num", "day"),
    sep = "-", convert = TRUE
  ) |>
  dplyr::mutate(
    month = month.name[month_num],               
    president = dplyr::case_when(               
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem",
      TRUE ~ NA_character_
    )
  ) |>
  dplyr::select(                                
    year, month, president,
    gov_gop, sen_gop, rep_gop,
    gov_dem, sen_dem, rep_dem
  ) |>
  dplyr::arrange(year, match(month, month.name))

dplyr::glimpse(pols_clean)
```

    ## Rows: 822
    ## Columns: 9
    ## $ year      <int> 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, …
    ## $ month     <chr> "January", "February", "March", "April", "May", "June", "Jul…
    ## $ president <chr> "dem", "dem", "dem", "dem", "dem", "dem", "dem", "dem", "dem…
    ## $ gov_gop   <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 22, 22, 22, …
    ## $ sen_gop   <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 53, 53, 53, …
    ## $ rep_gop   <dbl> 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, …
    ## $ gov_dem   <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, …
    ## $ sen_dem   <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 48, 48, 48, …
    ## $ rep_dem   <dbl> 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, …

``` r
snp_clean <- snp |>
  dplyr::mutate(
    date = as.Date(date, tryFormats = c("%Y-%m-%d", "%m/%d/%Y"))
  ) |>
  dplyr::transmute(
    year  = as.integer(format(date, "%Y")),
    month_num = as.integer(format(date, "%m")),
    month = month.name[month_num],
    close
  ) |>
  dplyr::arrange(year, month_num) |>
  dplyr::select(-month_num)

dplyr::glimpse(snp_clean)
```

    ## Rows: 787
    ## Columns: 3
    ## $ year  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
    ## $ month <chr> "January", "February", "March", "April", "May", "June", "July", …
    ## $ close <dbl> 1394.46, 1366.42, 1498.58, 1452.43, 1420.60, 1454.60, 1430.83, 1…

``` r
unemp_tidy <- unemp |>
  dplyr::rename(year = Year) |>
  tidyr::pivot_longer(
    cols = -year, names_to = "month", values_to = "unemployment_rate"
  ) |>
  dplyr::mutate(
    month = factor(month, levels = month.abb, labels = month.name),
    month = as.character(month)
  ) |>
  dplyr::arrange(year, match(month, month.name))

dplyr::glimpse(unemp_tidy)
```

    ## Rows: 816
    ## Columns: 3
    ## $ year              <dbl> 1948, 1948, 1948, 1948, 1948, 1948, 1948, 1948, 1948…
    ## $ month             <chr> "January", "February", "March", "April", "May", "Jun…
    ## $ unemployment_rate <dbl> 3.4, 3.8, 4.0, 3.9, 3.5, 3.6, 3.6, 3.9, 3.8, 3.7, 3.…

``` r
pols_snp <- dplyr::left_join(pols_clean, snp_clean, by = c("year", "month"))
merged   <- dplyr::left_join(pols_snp,  unemp_tidy, by = c("year", "month"))

dplyr::glimpse(merged)
```

    ## Rows: 822
    ## Columns: 11
    ## $ year              <dbl> 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947…
    ## $ month             <chr> "January", "February", "March", "April", "May", "Jun…
    ## $ president         <chr> "dem", "dem", "dem", "dem", "dem", "dem", "dem", "de…
    ## $ gov_gop           <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 22, …
    ## $ sen_gop           <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 53, …
    ## $ rep_gop           <dbl> 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 25…
    ## $ gov_dem           <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, …
    ## $ sen_dem           <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 48, …
    ## $ rep_dem           <dbl> 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 19…
    ## $ close             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ unemployment_rate <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3.4,…

``` r
dplyr::count(merged, year, sort = TRUE) |> head(3)
```

    ## # A tibble: 3 × 2
    ##    year     n
    ##   <dbl> <int>
    ## 1  1947    12
    ## 2  1948    12
    ## 3  1949    12

### About the datasets and the merged result

The `pols-month` dataset tracks the monthly number of U.S. national
politicians by party, together with the president’s affiliation. After
cleaning, it contains 822 rows and 9 columns. Key variables are `year`,
`month`, `president`, and the counts of governors, senators, and
representatives from both parties (`gov_*`, `sen_*`, `rep_*`).

The `snp` dataset gives monthly closing values of the S&P index. Once
processed, it keeps only `year`, `month`, and `close`, with a total of
787 observations.

The `unemployment` dataset provides monthly unemployment rates. After
being reshaped into a long format, it has 816 rows. The main variables
are `year`, `month`, and `unemployment_rate`.

When these three datasets are merged by `year` and `month`, the
resulting data frame `merged` includes 822 rows and 11 columns. The time
span goes from 1947 to 2015. In the final version, the most important
variables are the president’s party (`president`), the S&P closing value
(`close`), and the unemployment rate (`unemployment_rate`).
